#!/usr/bin/env sh

# debug only
echo POSTCOMMIT
set -x

# get hash of the last commit
last_commit_hash=$(git rev-parse HEAD)

git fetch
fetch_exit_code=$?
if [ $merge_exit_code -ne 0 ]; then
  echo "ERROR Fetch failed, undoing last commit"
  git reset --soft ${last_commit_hash}~1
  exit $merge_exit_code
fi

git merge

# if merge fails, revert the last commit
merge_exit_code=$?
if [ $merge_exit_code -ne 0 ]; then
  echo "ERROR Merge failed, undoing last commit"
  git merge --abort
  git reset --soft ${last_commit_hash}~1
  exit $merge_exit_code
fi

git push

push_exit_code=$?

if [ $push_exit_code -ne 0 ]; then
  echo "ERROR Push failed, undoing last commit"
  git reset --soft ${last_commit_hash}~1
  exit $push_exit_code
fi
