#!/usr/bin/env sh

# debug only
echo PREPUSH
set -x

# TODO push checkpoint data
# for each line on stdin, read the 2nd space-delimited field of hte local hash
# and get the contents of that in `.git/checkpoint/staged-blocks/<hash>/*`
# push those to the server, exit on failure
