#!/usr/bin/env sh

set -e

# debug only
echo PRECOMMIT
# set -x

# git fetch
# git merge

# # get current remote/branch
# remoteBranch=$(git rev-parse --abbrev-ref --symbolic-full-name @{u})

# git update-ref HEAD $remoteBranch

