// Thin re-export so this package can keep its existing import paths. The
// actual values live in versions.json and flow through
// src/core/common/src/versions-generated.ts (regenerated by set-version.js).
export {
  SERVER_API,
  MIN_SERVER_API,
  SERVER_VERSION,
} from "@checkpointvcs/common";
