// AUTO-GENERATED by scripts/set-version.js — do not edit manually.
// Source of truth: versions.json at the repo root.
//
// This file mirrors src/core/common/src/versions-generated.ts but lives in
// the app to avoid a type-resolution cycle:
//
//   common/utils/api.ts has `import type { AppRouter } from "@checkpointvcs/app"`,
//   so if app re-exported these from common, the app's own build would
//   transitively pull in its own dist/ as inputs and fail with TS5055.

export const SERVER_VERSION = "0.3.2";
export const SERVER_API = 1;
export const MIN_SERVER_API = 1;
