export enum ErrorNumber {
  EPERM = 1,
  ENOENT = 2,
  ESRCH = 3,
  EINTR = 4,
  EIO = 5,
  ENXIO = 6,
  E2BIG = 7,
  ENOEXEC = 8,
  EBADF = 9,
  ECHILD = 10,
  EAGAIN = 11,
  ENOMEM = 12,
  EACCES = 13,
  EFAULT = 14,
  EBUSY = 16,
  EEXIST = 17,
  EXDEV = 18,
  ENODEV = 19,
  ENOTDIR = 20,
  EISDIR = 21,
  ENFILE = 23,
  EMFILE = 24,
  ENOTTY = 25,
  EFBIG = 27,
  ENOSPC = 28,
  ESPIPE = 29,
  EROFS = 30,
  EMLINK = 31,
  EPIPE = 32,
  EDOM = 33,
  EDEADLK = 36,
  ENAMETOOLONG = 38,
  ENOLCK = 39,
  ENOSYS = 40,
  ENOTEMPTY = 41,
  EINVAL = 22,
  ERANGE = 34,
  EILSEQ = 42,
  STRUNCATE = 80,
  EADDRINUSE = 100,
  EADDRNOTAVAIL = 101,
  EAFNOSUPPORT = 102,
  EALREADY = 103,
  EBADMSG = 104,
  ECANCELED = 105,
  ECONNABORTED = 106,
  ECONNREFUSED = 107,
  ECONNRESET = 108,
  EDESTADDRREQ = 109,
  EHOSTUNREACH = 110,
  EIDRM = 111,
  EINPROGRESS = 112,
  EISCONN = 113,
  ELOOP = 114,
  EMSGSIZE = 115,
  ENETDOWN = 116,
  ENETRESET = 117,
  ENETUNREACH = 118,
  ENOBUFS = 119,
  ENODATA = 120,
  ENOLINK = 121,
  ENOMSG = 122,
  ENOPROTOOPT = 123,
  ENOSR = 124,
  ENOSTR = 125,
  ENOTCONN = 126,
  ENOTRECOVERABLE = 127,
  ENOTSOCK = 128,
  ENOTSUP = 129,
  EOPNOTSUPP = 130,
  EOTHER = 131,
  EOVERFLOW = 132,
  EOWNERDEAD = 133,
  EPROTO = 134,
  EPROTONOSUPPORT = 135,
  EPROTOTYPE = 136,
  ETIME = 137,
  ETIMEDOUT = 138,
  ETXTBSY = 139,
  EWOULDBLOCK = 140,
}

export const ErrorToString = {
  [ErrorNumber.E2BIG]: "Argument list too long.",
  [ErrorNumber.EACCES]: "Permission denied.",
  [ErrorNumber.EADDRINUSE]: "Address in use.",
  [ErrorNumber.EADDRNOTAVAIL]: "Address not available.",
  [ErrorNumber.EAFNOSUPPORT]: "Address family not supported.",
  [ErrorNumber.EAGAIN]:
    "Resource unavailable, try again (may be the same value as [EWOULDBLOCK]).",
  [ErrorNumber.EALREADY]: "Connection already in progress.",
  [ErrorNumber.EBADF]: "Bad file descriptor.",
  [ErrorNumber.EBADMSG]: "Bad message.",
  [ErrorNumber.EBUSY]: "Device or resource busy.",
  [ErrorNumber.ECANCELED]: "Operation canceled.",
  [ErrorNumber.ECHILD]: "No child processes.",
  [ErrorNumber.ECONNABORTED]: "Connection aborted.",
  [ErrorNumber.ECONNREFUSED]: "Connection refused.",
  [ErrorNumber.ECONNRESET]: "Connection reset.",
  [ErrorNumber.EDEADLK]: "Resource deadlock would occur.",
  [ErrorNumber.EDESTADDRREQ]: "Destination address required.",
  [ErrorNumber.EDOM]: "Mathematics argument out of domain of function.",
  [ErrorNumber.EEXIST]: "File exists.",
  [ErrorNumber.EFAULT]: "Bad address.",
  [ErrorNumber.EFBIG]: "File too large.",
  [ErrorNumber.EHOSTUNREACH]: "Host is unreachable.",
  [ErrorNumber.EIDRM]: "Identifier removed.",
  [ErrorNumber.EILSEQ]: "Illegal byte sequence.",
  [ErrorNumber.EINPROGRESS]: "Operation in progress.",
  [ErrorNumber.EINTR]: "Interrupted function.",
  [ErrorNumber.EINVAL]: "Invalid argument.",
  [ErrorNumber.EIO]: "I/O error.",
  [ErrorNumber.EISCONN]: "Socket is connected.",
  [ErrorNumber.EISDIR]: "Is a directory.",
  [ErrorNumber.ELOOP]: "Too many levels of symbolic links.",
  [ErrorNumber.EMFILE]: "Too many open files.",
  [ErrorNumber.EMLINK]: "Too many links.",
  [ErrorNumber.EMSGSIZE]: "Message too large.",
  [ErrorNumber.ENAMETOOLONG]: "Filename too long.",
  [ErrorNumber.ENETDOWN]: "Network is down.",
  [ErrorNumber.ENETRESET]: "Connection aborted by network.",
  [ErrorNumber.ENETUNREACH]: "Network unreachable.",
  [ErrorNumber.ENFILE]: "Too many files open in system.",
  [ErrorNumber.ENOBUFS]: "No buffer space available.",
  [ErrorNumber.ENODATA]:
    "[XSR] [Option Start] No message is available on the STREAM head read queue. [Option End]",
  [ErrorNumber.ENODEV]: "No such device.",
  [ErrorNumber.ENOENT]: "No such file or directory.",
  [ErrorNumber.ENOEXEC]: "Executable file format error.",
  [ErrorNumber.ENOLCK]: "No locks available.",
  [ErrorNumber.ENOLINK]: "Link has been severed (POSIX.1-2001).",
  [ErrorNumber.ENOMEM]: "Not enough space.",
  [ErrorNumber.ENOMSG]: "No message of the desired type.",
  [ErrorNumber.ENOPROTOOPT]: "Protocol not available.",
  [ErrorNumber.ENOSPC]: "No space left on device.",
  [ErrorNumber.ENOSR]: "[XSR] [Option Start] No STREAM resources. [Option End]",
  [ErrorNumber.ENOSTR]: "[XSR] [Option Start] Not a STREAM. [Option End]",
  [ErrorNumber.ENOSYS]: "Function not supported.",
  [ErrorNumber.ENOTCONN]: "The socket is not connected.",
  [ErrorNumber.ENOTDIR]: "Not a directory.",
  [ErrorNumber.ENOTEMPTY]: "Directory not empty.",
  [ErrorNumber.ENOTSOCK]: "Not a socket.",
  [ErrorNumber.ENOTSUP]: "Not supported.",
  [ErrorNumber.ENOTTY]: "Inappropriate I/O control operation.",
  [ErrorNumber.ENXIO]: "No such device or address.",
  [ErrorNumber.EOVERFLOW]: "Value too large to be stored in data type.",
  [ErrorNumber.EPERM]: "Operation not permitted.",
  [ErrorNumber.EPIPE]: "Broken pipe.",
  [ErrorNumber.EPROTO]: "Protocol error.",
  [ErrorNumber.EPROTONOSUPPORT]: "Protocol not supported.",
  [ErrorNumber.EPROTOTYPE]: "Protocol wrong type for socket.",
  [ErrorNumber.ERANGE]: "Result too large.",
  [ErrorNumber.EROFS]: "Read-only file system.",
  [ErrorNumber.ESPIPE]: "Invalid seek.",
  [ErrorNumber.ESRCH]: "No such process.",
  [ErrorNumber.ETIME]:
    "[XSR] [Option Start] Stream ioctl() timeout. [Option End]",
  [ErrorNumber.ETIMEDOUT]: "Connection timed out.",
  [ErrorNumber.ETXTBSY]: "Text file busy.",
  [ErrorNumber.EXDEV]: "Cross-device link. ",
};

export interface IErrorResult {
  error: ErrorNumber;
}
