# Possible values:
#   none
#   local
#   vault
#   aws-secrets-manager
#   azure-key-vault
#   gcp-secret-manager
provider: "local"

# This is how long we should reuse fetched secrets before fetching them again
cache-duration-seconds: 1800

# We don't generally recommend using the local provider for production,
# but it can be useful in some development scenarios.
local:
  # This is the path relative to the working directory directory
  # secrets should be stored in the following format:
  #   my_secret=my_value
  #   another_secret=another_value
  file-path: "/app/.secrets"

# This provider expects the VAULT_ROLE_ID and VAULT_SECRET_ID
# environment variables to be set for authentication.
vault:
  endpoint: "http://127.0.0.1:8200"
  namespace: "" # Leave empty if you're not using Vault namespaces
  path-prefix: "" # Prefix for secrets (e.g. "myproject/")
  kv-engine: "v2" # v1 or v2
  engine-name: "secret" # The name of the KV engine in Vault

# This provider expects the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY
# environment variables to be set for authentication.
aws-secrets-manager:
  region: "us-east-1"

# This provider expects the AZURE_TENANT_ID, AZURE_CLIENT_ID, and AZURE_CLIENT_SECRET
# environment variables to be set for authentication.
azure-key-vault:
  endpoint: "https://yourvault.vault.azure.net/"

gcp-secret-manager:
  project-id: "your-project-id"
  # Path to the Service Account JSON key file, relative to the backend root directory
  credentials-file: "gcp-credentials.json"
