// AUTO-GENERATED by scripts/set-version.js — do not edit manually.
// Source of truth: versions.json at the repo root.
#pragma once

namespace checkpoint {

// User-facing semver version of the bundled client installation.
constexpr const char* CLIENT_VERSION = "0.3.3";

// Integer daemon-API version this CLI was built against. Compared against
// the daemon's min_daemon_api at connect time.
constexpr int DAEMON_API = 1;

}  // namespace checkpoint
