package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"time"

	"fyne.io/systray"
)

var (
	mStatus         *systray.MenuItem
	mVersionMsg     *systray.MenuItem
	mUpdateStatus   *systray.MenuItem
	mUpdateDownload *systray.MenuItem
	mUpdateInstall  *systray.MenuItem
	mStart          *systray.MenuItem
	mStop           *systray.MenuItem
	mRestart        *systray.MenuItem
)

// trayDaemonAPI / trayClientVersion come from the generated version.go
// (regenerated by scripts/set-version.js from versions.json).
const trayDaemonAPI = DaemonAPI
const trayClientVersion = ClientVersion

// daemonVersionInfo mirrors the daemon's version.check response in the new
// integer-API model.
type daemonVersionInfo struct {
	ClientVersion string `json:"clientVersion"`
	DaemonAPI     int    `json:"daemonApi"`
	MinDaemonAPI  int    `json:"minDaemonApi"`
}

// updateStatus mirrors the daemon's UpdateStatus from src/core/daemon/src/updater.ts.
type updateStatus struct {
	CurrentVersion          string `json:"currentVersion"`
	LatestVersion           string `json:"latestVersion"`
	UpdateAvailable         bool   `json:"updateAvailable"`
	Checking                bool   `json:"checking"`
	Downloading             bool   `json:"downloading"`
	DownloadProgress        int    `json:"downloadProgress"`
	DownloadedInstallerPath string `json:"downloadedInstallerPath"`
	LastError               string `json:"lastError"`
}

func main() {
	systray.Run(onReady, onExit)
}

func onReady() {
	systray.SetIcon(trayIconData)
	systray.SetTooltip("Checkpoint VCS")

	mStatus = systray.AddMenuItem("Daemon: Checking...", "Daemon status")
	mStatus.Disable()
	mVersionMsg = systray.AddMenuItem("", "Version compatibility status")
	mVersionMsg.Disable()
	mVersionMsg.Hide()
	mUpdateStatus = systray.AddMenuItem("", "Update status")
	mUpdateStatus.Disable()
	mUpdateStatus.Hide()
	mUpdateDownload = systray.AddMenuItem("Download update", "Download the available Checkpoint update")
	mUpdateDownload.Hide()
	mUpdateInstall = systray.AddMenuItem("Install update & restart", "Run the installer and restart Checkpoint")
	mUpdateInstall.Hide()
	systray.AddSeparator()
	mStart = systray.AddMenuItem("Start Daemon", "Start the Checkpoint daemon service")
	mStop = systray.AddMenuItem("Stop Daemon", "Stop the Checkpoint daemon service")
	mRestart = systray.AddMenuItem("Restart Daemon", "Restart the Checkpoint daemon service")
	systray.AddSeparator()
	mOpenDesktop := systray.AddMenuItem("Open Desktop App", "Open Checkpoint Desktop")
	mViewLogs := systray.AddMenuItem("View Logs", "Open the Checkpoint log folder")
	systray.AddSeparator()
	mQuit := systray.AddMenuItem("Quit", "Quit the tray application")

	go updateDaemonStatus()

	go func() {
		ticker := time.NewTicker(10 * time.Second)
		defer ticker.Stop()
		for range ticker.C {
			updateDaemonStatus()
		}
	}()

	go func() {
		for {
			select {
			case <-mStart.ClickedCh:
				go handleStart()
			case <-mStop.ClickedCh:
				go handleStop()
			case <-mRestart.ClickedCh:
				go handleRestart()
			case <-mUpdateDownload.ClickedCh:
				go handleUpdateDownload()
			case <-mUpdateInstall.ClickedCh:
				go handleUpdateInstall()
			case <-mOpenDesktop.ClickedCh:
				go openDesktopApp()
			case <-mViewLogs.ClickedCh:
				go openLogs()
			case <-mQuit.ClickedCh:
				systray.Quit()
			}
		}
	}()
}

func onExit() {}

func handleStart() {
	mStart.Disable()
	mStatus.SetTitle("Daemon: Starting...")
	if err := startDaemonService(); err != nil {
		logTray("start daemon failed: %v", err)
		mStatus.SetTitle(fmt.Sprintf("Daemon: Error (%v)", err))
		mStart.Enable()
		return
	}
	time.Sleep(2 * time.Second)
	updateDaemonStatus()
}

func handleStop() {
	mStop.Disable()
	mRestart.Disable()
	mStatus.SetTitle("Daemon: Stopping...")
	if err := stopDaemonService(); err != nil {
		logTray("stop daemon failed: %v", err)
		mStatus.SetTitle(fmt.Sprintf("Daemon: Error (%v)", err))
		mStop.Enable()
		mRestart.Enable()
		return
	}
	time.Sleep(2 * time.Second)
	updateDaemonStatus()
}

func handleRestart() {
	mRestart.Disable()
	mStop.Disable()
	mStart.Disable()
	mStatus.SetTitle("Daemon: Restarting...")
	if err := restartDaemonService(); err != nil {
		logTray("restart daemon failed: %v", err)
		mStatus.SetTitle(fmt.Sprintf("Daemon: Error (%v)", err))
	}
	time.Sleep(3 * time.Second)
	updateDaemonStatus()
}

// logsDir returns the Checkpoint log directory (~/.checkpoint/logs), matching
// where the daemon writes daemon.log.
func logsDir() string {
	home, err := os.UserHomeDir()
	if err != nil {
		return filepath.Join(".checkpoint", "logs")
	}
	return filepath.Join(home, ".checkpoint", "logs")
}

// openLogs opens the Checkpoint log folder in the OS file manager.
func openLogs() {
	dir := logsDir()
	_ = os.MkdirAll(dir, 0o755)
	openPath(dir)
}

// logTray appends a timestamped line to ~/.checkpoint/logs/tray.log. Used to
// record service-control failures (e.g. a daemon that won't start) so they are
// visible via "View Logs" even when the daemon itself never produced a log.
func logTray(format string, args ...any) {
	dir := logsDir()
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return
	}
	f, err := os.OpenFile(
		filepath.Join(dir, "tray.log"),
		os.O_APPEND|os.O_CREATE|os.O_WRONLY,
		0o644,
	)
	if err != nil {
		return
	}
	defer f.Close()
	line := fmt.Sprintf(format, args...)
	fmt.Fprintf(f, "%s %s\n", time.Now().Format(time.RFC3339), line)
}

func getDaemonPort() int {
	home, err := os.UserHomeDir()
	if err != nil {
		return 13010
	}
	data, err := os.ReadFile(filepath.Join(home, ".checkpoint", "daemon.json"))
	if err != nil {
		return 13010
	}
	var cfg struct {
		DaemonPort int `json:"daemonPort"`
	}
	if err := json.Unmarshal(data, &cfg); err != nil || cfg.DaemonPort == 0 {
		return 13010
	}
	return cfg.DaemonPort
}

func isDaemonRunning() bool {
	port := getDaemonPort()
	client := &http.Client{Timeout: 2 * time.Second}
	resp, err := client.Get(fmt.Sprintf("http://127.0.0.1:%d", port))
	if err != nil {
		return false
	}
	resp.Body.Close()
	return true
}

func updateDaemonStatus() {
	if isDaemonRunning() {
		mStatus.SetTitle("Daemon: Running")
		mStart.Disable()
		mStop.Enable()
		mRestart.Enable()
		checkDaemonVersion()
		pollUpdateStatus()
	} else {
		mStatus.SetTitle("Daemon: Stopped")
		mStart.Enable()
		mStop.Disable()
		mRestart.Disable()
		mVersionMsg.Hide()
		mUpdateStatus.Hide()
		mUpdateDownload.Hide()
		mUpdateInstall.Hide()
	}
}

func checkDaemonVersion() {
	port := getDaemonPort()
	client := &http.Client{Timeout: 5 * time.Second}

	url := fmt.Sprintf(
		"http://127.0.0.1:%d/version.check?batch=1&input={}",
		port,
	)

	resp, err := client.Get(url)
	if err != nil {
		return
	}
	defer resp.Body.Close()

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return
	}

	// tRPC batch response: [{"result":{"data":{"json":{...}}}}]
	var batch []struct {
		Result struct {
			Data struct {
				JSON daemonVersionInfo `json:"json"`
			} `json:"data"`
		} `json:"result"`
	}
	if err := json.Unmarshal(body, &batch); err != nil || len(batch) == 0 {
		return
	}

	info := batch[0].Result.Data.JSON

	// Tray is bundled with the daemon, so this check trivially passes in
	// production, but it is kept for dev installs that may have mismatched binaries.
	if info.MinDaemonAPI > 0 && trayDaemonAPI < info.MinDaemonAPI {
		mVersionMsg.SetTitle(fmt.Sprintf(
			"⚠ Upgrade required (tray daemon_api %d < daemon's min %d)",
			trayDaemonAPI, info.MinDaemonAPI,
		))
		mVersionMsg.Show()
		return
	}

	mVersionMsg.Hide()
}

// pollUpdateStatus queries the daemon's updater.getStatus endpoint and
// adjusts the three update menu items based on the result. Silent on any
// error (we don't want a transient daemon hiccup to surface as a tray
// alert). Called from updateDaemonStatus on the 10-second ticker.
func pollUpdateStatus() {
	status, err := getUpdateStatus(getDaemonPort())
	if err != nil {
		mUpdateStatus.Hide()
		mUpdateDownload.Hide()
		mUpdateInstall.Hide()
		return
	}

	if !status.UpdateAvailable {
		mUpdateStatus.Hide()
		mUpdateDownload.Hide()
		mUpdateInstall.Hide()
		return
	}

	switch {
	case status.Downloading:
		mUpdateStatus.SetTitle(fmt.Sprintf(
			"Update: downloading %s (%d%%)",
			status.LatestVersion, status.DownloadProgress,
		))
		mUpdateStatus.Show()
		mUpdateDownload.Hide()
		mUpdateInstall.Hide()
	case status.DownloadedInstallerPath != "":
		mUpdateStatus.SetTitle(fmt.Sprintf(
			"Update: %s ready to install", status.LatestVersion,
		))
		mUpdateStatus.Show()
		mUpdateDownload.Hide()
		mUpdateInstall.Show()
	default:
		mUpdateStatus.SetTitle(fmt.Sprintf(
			"Update: %s available", status.LatestVersion,
		))
		mUpdateStatus.Show()
		mUpdateDownload.Show()
		mUpdateInstall.Hide()
	}
}

// getUpdateStatus queries the daemon's updater.getStatus tRPC endpoint and
// returns the unmarshalled status struct.
func getUpdateStatus(port int) (updateStatus, error) {
	client := &http.Client{Timeout: 5 * time.Second}
	url := fmt.Sprintf(
		"http://127.0.0.1:%d/updater.getStatus?batch=1&input={}", port,
	)
	resp, err := client.Get(url)
	if err != nil {
		return updateStatus{}, err
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return updateStatus{}, err
	}
	var batch []struct {
		Result struct {
			Data struct {
				JSON updateStatus `json:"json"`
			} `json:"data"`
		} `json:"result"`
	}
	if err := json.Unmarshal(body, &batch); err != nil || len(batch) == 0 {
		return updateStatus{}, fmt.Errorf("invalid response")
	}
	return batch[0].Result.Data.JSON, nil
}

// daemonMutate POSTs a tRPC mutation with an empty input object. Used by the
// updater download/apply click handlers.
func daemonMutate(port int, procedure string) error {
	url := fmt.Sprintf("http://127.0.0.1:%d/%s?batch=1", port, procedure)
	body := bytes.NewReader([]byte(`{"0":{"json":{}}}`))
	req, err := http.NewRequest("POST", url, body)
	if err != nil {
		return err
	}
	req.Header.Set("Content-Type", "application/json")
	client := &http.Client{Timeout: 30 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	return nil
}

func handleUpdateDownload() {
	mUpdateDownload.Disable()
	if err := daemonMutate(getDaemonPort(), "updater.downloadUpdate"); err != nil {
		mUpdateStatus.SetTitle(fmt.Sprintf("Update: download failed (%v)", err))
		mUpdateDownload.Enable()
		return
	}
	// The next pollUpdateStatus tick (≤ 10s) will surface progress and the
	// "ready to install" transition.
	mUpdateDownload.Enable()
}

func handleUpdateInstall() {
	mUpdateInstall.Disable()
	// applyUpdate spawns the installer detached and exits the daemon, so the
	// HTTP request may not return cleanly; treat connection-reset as success.
	_ = daemonMutate(getDaemonPort(), "updater.applyUpdate")
	mUpdateStatus.SetTitle("Update: installer launched, restarting...")
}

// The tray icon is embedded per-platform (ICO on Windows, PNG elsewhere) in
// icon_windows.go / icon_other.go as trayIconData.
