package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"time"

	"fyne.io/systray"
)

var (
	mStatus         *systray.MenuItem
	mVersionMsg     *systray.MenuItem
	mUpdateStatus   *systray.MenuItem
	mUpdateDownload *systray.MenuItem
	mUpdateInstall  *systray.MenuItem
	mStart          *systray.MenuItem
	mStop           *systray.MenuItem
	mRestart        *systray.MenuItem
	mMcp            *systray.MenuItem
)

// trayDaemonAPI / trayClientVersion come from the generated version.go
// (regenerated by scripts/set-version.js from versions.json).
const trayDaemonAPI = DaemonAPI
const trayClientVersion = ClientVersion

// daemonVersionInfo mirrors the daemon's version.check response in the new
// integer-API model.
type daemonVersionInfo struct {
	ClientVersion string `json:"clientVersion"`
	DaemonAPI     int    `json:"daemonApi"`
	MinDaemonAPI  int    `json:"minDaemonApi"`
}

// mcpStatus mirrors the daemon's McpStatus from src/core/daemon/src/mcp-server.ts.
type mcpStatus struct {
	Enabled bool `json:"enabled"`
	Running bool `json:"running"`
	Port    int  `json:"port"`
}

// updateStatus mirrors the daemon's UpdateStatus from src/core/daemon/src/updater.ts.
type updateStatus struct {
	CurrentVersion          string `json:"currentVersion"`
	LatestVersion           string `json:"latestVersion"`
	UpdateAvailable         bool   `json:"updateAvailable"`
	Checking                bool   `json:"checking"`
	Downloading             bool   `json:"downloading"`
	DownloadProgress        int    `json:"downloadProgress"`
	DownloadedInstallerPath string `json:"downloadedInstallerPath"`
	LastError               string `json:"lastError"`
}

func main() {
	systray.Run(onReady, onExit)
}

func onReady() {
	systray.SetIcon(trayIconData)
	systray.SetTooltip("Checkpoint VCS")

	mVersion := systray.AddMenuItem("Checkpoint v"+trayClientVersion, "Installed Checkpoint version")
	mVersion.Disable()
	systray.AddSeparator()

	mStatus = systray.AddMenuItem("Daemon: Checking...", "Daemon status")
	mStatus.Disable()
	mVersionMsg = systray.AddMenuItem("", "Version compatibility status")
	mVersionMsg.Disable()
	mVersionMsg.Hide()
	mUpdateStatus = systray.AddMenuItem("", "Update status")
	mUpdateStatus.Disable()
	mUpdateStatus.Hide()
	mUpdateDownload = systray.AddMenuItem("Download update", "Download the available Checkpoint update")
	mUpdateDownload.Hide()
	mUpdateInstall = systray.AddMenuItem("Install update & restart", "Run the installer and restart Checkpoint")
	mUpdateInstall.Hide()
	systray.AddSeparator()
	mStart = systray.AddMenuItem("Start Daemon", "Start the Checkpoint daemon service")
	mStop = systray.AddMenuItem("Stop Daemon", "Stop the Checkpoint daemon service")
	mRestart = systray.AddMenuItem("Restart Daemon", "Restart the Checkpoint daemon service")
	mMcp = systray.AddMenuItemCheckbox(
		"MCP Server",
		"Enable or disable the daemon's MCP server for AI tools",
		false,
	)
	mMcp.Disable()
	systray.AddSeparator()
	// Team Sync status + "Sync Latest". Both stay hidden until the daemon
	// reports at least one workspace.
	initTeamSyncMenu()
	systray.AddSeparator()
	mOpenDesktop := systray.AddMenuItem("Open Desktop App", "Open Checkpoint Desktop")
	mViewLogs := systray.AddMenuItem("View Logs", "Open the Checkpoint log folder")
	systray.AddSeparator()
	mQuit := systray.AddMenuItem("Quit", "Quit the tray application")

	// On Windows the daemon is launched and supervised by the tray (there is no
	// Windows service), so start it if it isn't already running. On macOS/Linux
	// launchd/systemd normally start it; the running check keeps this a no-op
	// there.
	go func() {
		if !isDaemonRunning() {
			if err := startDaemonService(); err != nil {
				logTray("auto-start daemon failed: %v", err)
			}
			time.Sleep(2 * time.Second)
		}
		updateDaemonStatus()
	}()

	go func() {
		ticker := time.NewTicker(10 * time.Second)
		defer ticker.Stop()
		for range ticker.C {
			updateDaemonStatus()
		}
	}()

	startTeamSyncPoll()

	go func() {
		for {
			select {
			case <-mStart.ClickedCh:
				go handleStart()
			case <-mStop.ClickedCh:
				go handleStop()
			case <-mRestart.ClickedCh:
				go handleRestart()
			case <-mMcp.ClickedCh:
				go handleMcpToggle()
			case <-mUpdateDownload.ClickedCh:
				go handleUpdateDownload()
			case <-mUpdateInstall.ClickedCh:
				go handleUpdateInstall()
			case <-mOpenDesktop.ClickedCh:
				go openDesktopApp()
			case <-mViewLogs.ClickedCh:
				go openLogs()
			case <-mQuit.ClickedCh:
				systray.Quit()
			}
		}
	}()
}

func onExit() {}

func handleStart() {
	mStart.Disable()
	mStatus.SetTitle("Daemon: Starting...")
	logTray("start: requested")
	if err := startDaemonService(); err != nil {
		logTray("start daemon failed: %v", err)
		mStatus.SetTitle("Daemon: Error")
		mStart.Enable()
		return
	}
	time.Sleep(2 * time.Second)
	updateDaemonStatus()
}

func handleStop() {
	mStop.Disable()
	mRestart.Disable()
	mStatus.SetTitle("Daemon: Stopping...")
	if err := stopDaemonService(); err != nil {
		logTray("stop daemon failed: %v", err)
		mStatus.SetTitle("Daemon: Error")
		mStop.Enable()
		mRestart.Enable()
		return
	}
	time.Sleep(2 * time.Second)
	updateDaemonStatus()
}

func handleRestart() {
	mRestart.Disable()
	mStop.Disable()
	mStart.Disable()
	mStatus.SetTitle("Daemon: Restarting...")
	if err := restartDaemonService(); err != nil {
		logTray("restart daemon failed: %v", err)
		mStatus.SetTitle("Daemon: Error")
	}
	time.Sleep(3 * time.Second)
	updateDaemonStatus()
}

// logsDir returns the Checkpoint log directory (~/.checkpoint/logs), matching
// where the daemon writes daemon.log.
func logsDir() string {
	home, err := os.UserHomeDir()
	if err != nil {
		return filepath.Join(".checkpoint", "logs")
	}
	return filepath.Join(home, ".checkpoint", "logs")
}

// openLogs opens the Checkpoint log folder in the OS file manager.
func openLogs() {
	dir := logsDir()
	_ = os.MkdirAll(dir, 0o755)
	openPath(dir)
}

// logTray appends a timestamped line to ~/.checkpoint/logs/tray.log. Used to
// record service-control failures (e.g. a daemon that won't start) so they are
// visible via "View Logs" even when the daemon itself never produced a log.
func logTray(format string, args ...any) {
	dir := logsDir()
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return
	}
	f, err := os.OpenFile(
		filepath.Join(dir, "tray.log"),
		os.O_APPEND|os.O_CREATE|os.O_WRONLY,
		0o644,
	)
	if err != nil {
		return
	}
	defer f.Close()
	line := fmt.Sprintf(format, args...)
	fmt.Fprintf(f, "%s %s\n", time.Now().Format(time.RFC3339), line)
}

func getDaemonPort() int {
	home, err := os.UserHomeDir()
	if err != nil {
		return 13010
	}
	data, err := os.ReadFile(filepath.Join(home, ".checkpoint", "daemon.json"))
	if err != nil {
		return 13010
	}
	var cfg struct {
		DaemonPort int `json:"daemonPort"`
	}
	if err := json.Unmarshal(data, &cfg); err != nil || cfg.DaemonPort == 0 {
		return 13010
	}
	return cfg.DaemonPort
}

func isDaemonRunning() bool {
	port := getDaemonPort()
	client := &http.Client{Timeout: 2 * time.Second}
	resp, err := client.Get(fmt.Sprintf("http://127.0.0.1:%d", port))
	if err != nil {
		return false
	}
	resp.Body.Close()
	return true
}

func updateDaemonStatus() {
	if isDaemonRunning() {
		mStatus.SetTitle("Daemon: Running")
		mStart.Disable()
		mStop.Enable()
		mRestart.Enable()
		checkDaemonVersion()
		pollUpdateStatus()
		pollMcpStatus()
	} else {
		mStatus.SetTitle("Daemon: Stopped")
		mStart.Enable()
		mStop.Disable()
		mRestart.Disable()
		mMcp.Disable()
		mVersionMsg.Hide()
		mUpdateStatus.Hide()
		mUpdateDownload.Hide()
		mUpdateInstall.Hide()
	}
}

// pollMcpStatus syncs the MCP checkbox with the daemon's mcp.getStatus. The
// item stays disabled when the daemon doesn't answer (e.g. an older daemon
// without the MCP feature).
func pollMcpStatus() {
	status, err := getMcpStatus(getDaemonPort())
	if err != nil {
		mMcp.Disable()
		return
	}

	mMcp.Enable()
	if status.Enabled {
		mMcp.Check()
	} else {
		mMcp.Uncheck()
	}
	if status.Running {
		mMcp.SetTitle(fmt.Sprintf("MCP Server (port %d)", status.Port))
	} else {
		mMcp.SetTitle("MCP Server")
	}
}

// daemonQuery performs a tRPC GET query against the daemon and decodes the
// procedure's result into out. Pass "" as inputJSON for input-less procedures;
// otherwise pass the raw input object, which is wrapped for the batch link and
// superjson transformer the daemon is configured with.
func daemonQuery(port int, procedure string, inputJSON string, out any) error {
	input := "{}"
	if inputJSON != "" {
		input = `{"0":{"json":` + inputJSON + `}}`
	}

	endpoint := fmt.Sprintf(
		"http://127.0.0.1:%d/%s?batch=1&input=%s",
		port, procedure, url.QueryEscape(input),
	)

	client := &http.Client{Timeout: 10 * time.Second}
	resp, err := client.Get(endpoint)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return err
	}

	// tRPC batch response: [{"result":{"data":{"json":...}}}], or an "error"
	// member in place of "result" when the procedure threw.
	var batch []struct {
		Result struct {
			Data struct {
				JSON json.RawMessage `json:"json"`
			} `json:"data"`
		} `json:"result"`
		Error *struct {
			JSON struct {
				Message string `json:"message"`
			} `json:"json"`
		} `json:"error"`
	}
	if err := json.Unmarshal(body, &batch); err != nil || len(batch) == 0 {
		return fmt.Errorf("%s: invalid response", procedure)
	}
	if batch[0].Error != nil {
		return fmt.Errorf("%s: %s", procedure, batch[0].Error.JSON.Message)
	}
	if len(batch[0].Result.Data.JSON) == 0 {
		return fmt.Errorf("%s: empty result", procedure)
	}

	return json.Unmarshal(batch[0].Result.Data.JSON, out)
}

// getMcpStatus queries the daemon's mcp.getStatus tRPC endpoint.
func getMcpStatus(port int) (mcpStatus, error) {
	var status mcpStatus
	if err := daemonQuery(port, "mcp.getStatus", "", &status); err != nil {
		return mcpStatus{}, err
	}
	return status, nil
}

// handleMcpToggle flips the daemon's MCP server on or off. The daemon applies
// the change immediately and persists it to daemon.json.
func handleMcpToggle() {
	mMcp.Disable()
	port := getDaemonPort()

	status, err := getMcpStatus(port)
	if err != nil {
		logTray("mcp toggle: failed to read status: %v", err)
		pollMcpStatus()
		return
	}

	input := fmt.Sprintf(`{"enabled":%t}`, !status.Enabled)
	if err := daemonMutateInput(port, "mcp.setEnabled", input); err != nil {
		logTray("mcp toggle failed: %v", err)
	}
	pollMcpStatus()
}

func checkDaemonVersion() {
	var info daemonVersionInfo
	if err := daemonQuery(getDaemonPort(), "version.check", "", &info); err != nil {
		return
	}

	// Tray is bundled with the daemon, so this check trivially passes in
	// production, but it is kept for dev installs that may have mismatched binaries.
	if info.MinDaemonAPI > 0 && trayDaemonAPI < info.MinDaemonAPI {
		logTray("daemon API version %d is too old for this tray (requires ≥ %d, tray: %d)",
			info.DaemonAPI, info.MinDaemonAPI, trayDaemonAPI,
		)
		mVersionMsg.SetTitle("⚠ Upgrade required")
		mVersionMsg.Show()
		return
	}

	mVersionMsg.Hide()
}

// pollUpdateStatus queries the daemon's updater.getStatus endpoint and
// adjusts the three update menu items based on the result. Silent on any
// error (we don't want a transient daemon hiccup to surface as a tray
// alert). Called from updateDaemonStatus on the 10-second ticker.
func pollUpdateStatus() {
	status, err := getUpdateStatus(getDaemonPort())
	if err != nil {
		mUpdateStatus.Hide()
		mUpdateDownload.Hide()
		mUpdateInstall.Hide()
		return
	}

	if !status.UpdateAvailable {
		mUpdateStatus.Hide()
		mUpdateDownload.Hide()
		mUpdateInstall.Hide()
		return
	}

	switch {
	case status.Downloading:
		mUpdateStatus.SetTitle(fmt.Sprintf(
			"Update: downloading %s (%d%%)",
			status.LatestVersion, status.DownloadProgress,
		))
		mUpdateStatus.Show()
		mUpdateDownload.Hide()
		mUpdateInstall.Hide()
	case status.DownloadedInstallerPath != "":
		mUpdateStatus.SetTitle(fmt.Sprintf(
			"Update: %s ready to install", status.LatestVersion,
		))
		mUpdateStatus.Show()
		mUpdateDownload.Hide()
		mUpdateInstall.Show()
	default:
		mUpdateStatus.SetTitle(fmt.Sprintf(
			"Update: %s available", status.LatestVersion,
		))
		mUpdateStatus.Show()
		mUpdateDownload.Show()
		mUpdateInstall.Hide()
	}
}

// getUpdateStatus queries the daemon's updater.getStatus tRPC endpoint and
// returns the unmarshalled status struct.
func getUpdateStatus(port int) (updateStatus, error) {
	var status updateStatus
	if err := daemonQuery(port, "updater.getStatus", "", &status); err != nil {
		return updateStatus{}, err
	}
	return status, nil
}

// daemonMutate POSTs a tRPC mutation with an empty input object. Used by the
// updater download/apply click handlers.
func daemonMutate(port int, procedure string) error {
	return daemonMutateInput(port, procedure, "{}")
}

// daemonMutateInput POSTs a tRPC mutation with the given JSON input. A
// procedure that throws answers 200 with an "error" member rather than an HTTP
// error status, so the body is decoded to surface the message to the caller.
func daemonMutateInput(port int, procedure string, inputJSON string) error {
	endpoint := fmt.Sprintf("http://127.0.0.1:%d/%s?batch=1", port, procedure)
	body := bytes.NewReader([]byte(`{"0":{"json":` + inputJSON + `}}`))
	req, err := http.NewRequest("POST", endpoint, body)
	if err != nil {
		return err
	}
	req.Header.Set("Content-Type", "application/json")
	client := &http.Client{Timeout: 30 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		// The mutation was accepted; we just couldn't read the reply. Some
		// mutations (updater.applyUpdate) kill the daemon before responding.
		return nil
	}

	var batch []struct {
		Error *struct {
			JSON struct {
				Message string `json:"message"`
			} `json:"json"`
		} `json:"error"`
	}
	if err := json.Unmarshal(respBody, &batch); err != nil || len(batch) == 0 {
		return nil
	}
	if batch[0].Error != nil {
		return fmt.Errorf("%s: %s", procedure, batch[0].Error.JSON.Message)
	}
	return nil
}

func handleUpdateDownload() {
	mUpdateDownload.Disable()
	if err := daemonMutate(getDaemonPort(), "updater.downloadUpdate"); err != nil {
		logTray("failed to start update download: %v", err)
		mUpdateStatus.SetTitle("Update: download failed")
		mUpdateDownload.Enable()
		return
	}
	// The next pollUpdateStatus tick (≤ 10s) will surface progress and the
	// "ready to install" transition.
	mUpdateDownload.Enable()
}

func handleUpdateInstall() {
	mUpdateInstall.Disable()
	// applyUpdate spawns the installer detached and exits the daemon, so the
	// HTTP request may not return cleanly; treat connection-reset as success.
	_ = daemonMutate(getDaemonPort(), "updater.applyUpdate")
	mUpdateStatus.SetTitle("Update: installer launched, restarting...")
}

// The tray icon is embedded per-platform (ICO on Windows, PNG elsewhere) in
// icon_windows.go / icon_other.go as trayIconData.
