// AUTO-GENERATED by scripts/set-version.js — do not edit manually.
// Source of truth: versions.json at the repo root.
package main

// User-facing semver version of the bundled client installation.
const ClientVersion = "0.4.1"

// Integer daemon-API version this tray was built against. Compared against
// the daemon's min_daemon_api at connect time.
const DaemonAPI = 1
