// AUTO-GENERATED by scripts/set-version.js — do not edit manually.
// Source of truth: versions.json at the repo root.
//
// User-facing semver versions:
//   SERVER_VERSION — src/app + src/core/server share this
//   CLIENT_VERSION — src/core/daemon + src/clients/{desktop,cli,tray} share this
//
// Integer API versions. Bump only when there's an actual wire-format break:
//   SERVER_API     — current server API the running server speaks
//   MIN_SERVER_API — minimum server-API a connecting daemon must speak
//   DAEMON_API     — current daemon API the running daemon speaks
//   MIN_DAEMON_API — minimum daemon-API a connecting client must speak

export const SERVER_VERSION = "0.4.2";
export const CLIENT_VERSION = "0.4.2";
export const SERVER_API = 1;
export const MIN_SERVER_API = 1;
export const DAEMON_API = 1;
export const MIN_DAEMON_API = 1;
