services:
  master:
    image: checkpointvcs/seaweedfs:local
    build:
      context: ../seaweedfs/docker
      dockerfile: Dockerfile.local
    pull_policy: never
    ports:
      - 9333:9333
      - 19333:19333
      - 9324:9324
    command: "master -ip=master -ip.bind=0.0.0.0"
    volumes:
      - ./.data/seaweed-config/security.toml:/etc/seaweedfs/security.toml

  volume:
    image: checkpointvcs/seaweedfs:local
    build:
      context: ../seaweedfs/docker
      dockerfile: Dockerfile.local
    pull_policy: never
    ports:
      - 8080:8080
      - 18080:18080
    command: 'volume -mserver="master:9333" -ip.bind=0.0.0.0 -port=8080'
    depends_on:
      - master
    volumes:
      - ./.data/volume:/data
      - ./.data/seaweed-config/security.toml:/etc/seaweedfs/security.toml

  filer:
    image: checkpointvcs/seaweedfs:local
    build:
      context: ../seaweedfs/docker
      dockerfile: Dockerfile.local
    pull_policy: never
    ports:
      - 8888:8888
      - 18888:18888
      - 9326:9326
    command: 'filer -master="master:9333" -ip.bind=0.0.0.0 -metricsPort=9326'
    tty: true
    stdin_open: true
    depends_on:
      - master
      - volume
    volumes:
      - ./.data/seaweed-config/filer.toml:/etc/seaweedfs/filer.toml
      - ./.data/seaweed-config/security.toml:/etc/seaweedfs/security.toml

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./.data/redis:/data

  # app:
  #   build:
  #     context: ../app
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8910:8910
  #     - 8911:8911
