// Source of truth for all versions in this repo is `./versions.json`. This
// script bumps the user-facing semver versions (server_version + client_version)
// in that file, then propagates them to every place a version is required:
//
//   - workspace package.json files (split by server vs. client)
//   - generated TypeScript constants (src/core/common/src/versions-generated.ts)
//   - generated C++ header (src/clients/cli/version.hpp)
//   - generated Go file (src/clients/tray/version.go)
//   - Unreal plugin descriptor (Version int auto-incremented, VersionName set)
//
// The four integer API versions (server_api, min_server_api, daemon_api,
// min_daemon_api) are NOT touched — they're bumped manually in versions.json
// when there's an actual wire-format break.
//
// Usage:
//   node scripts/set-version.js <semver>            # bumps both server + client
//   node scripts/set-version.js --client <semver>   # bumps client only
//   node scripts/set-version.js --server <semver>   # bumps server only
//   (combine --client and --server to set them independently)

const fs = require("fs");
const path = require("path");

const repoRoot = path.resolve(__dirname, "..");
const versionsJsonPath = path.join(repoRoot, "versions.json");

// ─── Argument parsing ───────────────────────────────────────────────

const args = process.argv.slice(2);
let positional = null;
let clientArg = null;
let serverArg = null;

for (let i = 0; i < args.length; i++) {
  const a = args[i];
  if (a === "--client") {
    clientArg = args[++i];
  } else if (a === "--server") {
    serverArg = args[++i];
  } else if (a.startsWith("--client=")) {
    clientArg = a.slice("--client=".length);
  } else if (a.startsWith("--server=")) {
    serverArg = a.slice("--server=".length);
  } else if (!a.startsWith("--")) {
    positional = a;
  }
}

if (!positional && !clientArg && !serverArg) {
  console.error(
    "usage: node scripts/set-version.js <semver> [--client <x>] [--server <x>]",
  );
  process.exit(1);
}

const semverRe = /^\d+\.\d+\.\d+(?:-[\w.-]+)?(?:\+[\w.-]+)?$/;
function assertSemver(v, label) {
  if (!semverRe.test(v)) {
    console.error(`invalid semver for ${label}: ${v}`);
    process.exit(1);
  }
}

// Resolve final values: explicit flags win, else positional applies to both.
const newClient = clientArg ?? positional;
const newServer = serverArg ?? positional;
if (newClient) assertSemver(newClient, "client_version");
if (newServer) assertSemver(newServer, "server_version");

// ─── Read versions.json ─────────────────────────────────────────────

const versions = JSON.parse(fs.readFileSync(versionsJsonPath, "utf8"));

if (newClient) versions.client_version = newClient;
if (newServer) versions.server_version = newServer;

// ─── Helpers ─────────────────────────────────────────────────────────

function read(rel) {
  return fs.readFileSync(path.join(repoRoot, rel), "utf8");
}
function write(rel, content) {
  fs.writeFileSync(path.join(repoRoot, rel), content);
  console.log(`  wrote ${rel}`);
}
function updateJson(rel, mutate, indent) {
  const raw = read(rel);
  const trailingNewline = raw.endsWith("\n") ? "\n" : "";
  const data = JSON.parse(raw);
  mutate(data);
  write(rel, JSON.stringify(data, null, indent) + trailingNewline);
}

// ─── Write versions.json ─────────────────────────────────────────────

console.log(
  `Setting versions: server=${versions.server_version}, client=${versions.client_version}`,
);
write("versions.json", JSON.stringify(versions, null, 2) + "\n");

// ─── Workspace package.json files ───────────────────────────────────

const SERVER_PACKAGES = [
  "src/app/package.json",
  "src/core/server/package.json",
];
const CLIENT_PACKAGES = [
  "src/core/package.json",
  "src/core/common/package.json",
  "src/core/daemon/package.json",
  "src/clients/desktop/package.json",
];

for (const rel of SERVER_PACKAGES) {
  updateJson(
    rel,
    (pkg) => {
      pkg.version = versions.server_version;
    },
    2,
  );
}
for (const rel of CLIENT_PACKAGES) {
  updateJson(
    rel,
    (pkg) => {
      pkg.version = versions.client_version;
    },
    2,
  );
}

// ─── Generated TypeScript constants (consumed via @checkpointvcs/common) ───

write(
  "src/core/common/src/versions-generated.ts",
  `// AUTO-GENERATED by scripts/set-version.js — do not edit manually.
// Source of truth: versions.json at the repo root.
//
// User-facing semver versions:
//   SERVER_VERSION — src/app + src/core/server share this
//   CLIENT_VERSION — src/core/daemon + src/clients/{desktop,cli,tray} share this
//
// Integer API versions. Bump only when there's an actual wire-format break:
//   SERVER_API     — current server API the running server speaks
//   MIN_SERVER_API — minimum server-API a connecting daemon must speak
//   DAEMON_API     — current daemon API the running daemon speaks
//   MIN_DAEMON_API — minimum daemon-API a connecting client must speak

export const SERVER_VERSION = ${JSON.stringify(versions.server_version)};
export const CLIENT_VERSION = ${JSON.stringify(versions.client_version)};
export const SERVER_API = ${versions.server_api};
export const MIN_SERVER_API = ${versions.min_server_api};
export const DAEMON_API = ${versions.daemon_api};
export const MIN_DAEMON_API = ${versions.min_daemon_api};
`,
);

// ─── Generated C++ header for the CLI ───────────────────────────────

write(
  "src/clients/cli/version.hpp",
  `// AUTO-GENERATED by scripts/set-version.js — do not edit manually.
// Source of truth: versions.json at the repo root.
#pragma once

namespace checkpoint {

// User-facing semver version of the bundled client installation.
constexpr const char* CLIENT_VERSION = ${JSON.stringify(versions.client_version)};

// Integer daemon-API version this CLI was built against. Compared against
// the daemon's min_daemon_api at connect time.
constexpr int DAEMON_API = ${versions.daemon_api};

}  // namespace checkpoint
`,
);

// ─── Generated Go file for the tray ─────────────────────────────────

write(
  "src/clients/tray/version.go",
  `// AUTO-GENERATED by scripts/set-version.js — do not edit manually.
// Source of truth: versions.json at the repo root.
package main

// User-facing semver version of the bundled client installation.
const ClientVersion = ${JSON.stringify(versions.client_version)}

// Integer daemon-API version this tray was built against. Compared against
// the daemon's min_daemon_api at connect time.
const DaemonAPI = ${versions.daemon_api}
`,
);

// ─── Unreal plugin descriptor ───────────────────────────────────────
// The plugin's API_VERSION (in CheckpointDaemonClient.h) is managed
// independently — the Unreal plugin has its own release cadence and may run
// against an older daemon_api than the current versions.json. This script
// only bumps the descriptor's VersionName (semver shown in the editor) and
// auto-increments the integer Version (Unreal's required ascending counter).
{
  const rel = "src/clients/unreal/CheckpointSourceControl.uplugin";
  let nextVersion;
  updateJson(
    rel,
    (data) => {
      const current = typeof data.Version === "number" ? data.Version : 0;
      nextVersion = current + 1;
      data.Version = nextVersion;
      data.VersionName = versions.client_version;
    },
    "\t",
  );
  console.log(
    `  Unreal plugin: Version=${nextVersion}, VersionName=${versions.client_version}`,
  );
}

console.log("done");
