// AUTO-GENERATED by scripts/set-version.js from versions.json. Do not edit by hand.
namespace Checkpoint.Api;

/// <summary>
/// Version constants stamped from the repo-root versions.json.
/// </summary>
public static class CheckpointVersion
{
	/// <summary>Version of this client library.</summary>
	public const string ClientVersion = "0.4.15";

	/// <summary>Server API level this client was built against.</summary>
	public const int ServerApi = 2;
}
