// Thin re-export so this package can keep its existing import paths. The
// actual values live in versions.json and flow through
// src/core/common/src/versions-generated.ts (regenerated by set-version.js).
//
// SERVER_API is what server API this daemon was built against — used when
// checking server compatibility (`SERVER_API >= server.min_server_api`).
// MIN_DAEMON_API is published to connecting clients (cli/desktop/tray/unreal)
// so they can verify they're not too old.
export {
  DAEMON_API,
  MIN_DAEMON_API,
  SERVER_API,
  CLIENT_VERSION,
} from "@checkpointvcs/common";
