import {
  promises as fs,
  existsSync,
  createWriteStream,
  readFileSync,
} from "fs";
import path from "path";
import { homedir, platform, arch } from "os";
import https from "https";
import http from "http";
import { Logger } from "./logging.js";
import { DaemonConfig } from "./daemon-config.js";
import { CLIENT_VERSION } from "@checkpointvcs/common";

/**
 * Delivery stream this client follows.
 *
 *   release  Stable builds. Reads the repository's "latest" GitHub release,
 *            which nightlies are explicitly excluded from (make_latest: false).
 *   nightly  Automated builds off main, published by .github/workflows/release.yaml
 *            as a rolling prerelease on a fixed tag. Versions carry a
 *            `-nightly.<timestamp>.g<sha>` prerelease suffix.
 */
export type UpdateChannel = "release" | "nightly";

export interface UpdateStatus {
  currentVersion: string;
  latestVersion: string | null;
  updateAvailable: boolean;
  checking: boolean;
  downloading: boolean;
  downloadProgress: number;
  downloadedInstallerPath: string | null;
  lastCheckTime: number | null;
  lastError: string | null;
  channel: UpdateChannel;
}

export interface UpdaterConfig {
  /** GitHub repository in "owner/repo" format */
  repository: string;
  /** Check interval in milliseconds (default: 6 hours) */
  checkIntervalMs: number;
  /** Whether auto-check is enabled */
  enabled: boolean;
  /** Delivery stream to follow */
  channel: UpdateChannel;
  /**
   * Tag holding the rolling nightly prerelease. Must match `nightlyTag` in
   * .github/release-config.json.
   */
  nightlyTag: string;
}

const DEFAULT_CONFIG: UpdaterConfig = {
  repository: "Incanta/Checkpoint",
  checkIntervalMs: 6 * 60 * 60 * 1000, // 6 hours
  enabled: true,
  channel: "release",
  nightlyTag: "nightly",
};

interface GitHubRelease {
  tag_name: string;
  name: string;
  draft: boolean;
  prerelease: boolean;
  assets: GitHubAsset[];
  html_url: string;
}

interface GitHubAsset {
  name: string;
  browser_download_url: string;
  size: number;
  content_type: string;
}

function getCurrentVersion(): string {
  // CLIENT_VERSION is baked in at build time via src/core/common/src/versions-generated.ts
  // (regenerated by scripts/set-version.js from versions.json). The esbuild
  // bundle includes common, so this value travels with the daemon bundle.
  if (CLIENT_VERSION) return CLIENT_VERSION;

  // Legacy fallbacks for the rare case where the bundled constant isn't set:
  const envVersion = process.env["CHECKPOINT_VERSION"];
  if (envVersion) return envVersion;

  try {
    const versionFile = path.join(path.dirname(process.execPath), "VERSION");
    if (existsSync(versionFile)) {
      return (readFileSync(versionFile, "utf-8") as string).trim();
    }
  } catch {
    // ignore
  }

  return "0.0.0-dev";
}

function getInstallerAssetPattern(): string {
  const p = platform();
  const a = arch();

  switch (p) {
    case "win32":
      return "Checkpoint-Windows-x64-.*-Setup\\.exe$";
    case "linux":
      return "Checkpoint-Linux-amd64-.*\\.deb$";
    case "darwin":
      if (a === "arm64") {
        return "Checkpoint-macOS-arm64-.*\\.pkg$";
      }
      return "Checkpoint-macOS-x64-.*\\.pkg$";
    default:
      return "";
  }
}

/**
 * Pull the semver embedded in a downloaded installer's filename, e.g.
 * "0.4.11" from "Checkpoint-Windows-x64-0.4.11-Setup.exe" (also matches the
 * .deb/.rpm/.pkg names). Returns null when no version can be found.
 *
 * Anchored on the whole filename because nightly versions contain dashes of
 * their own ("0.5.0-nightly.202609030800.g1a2b3c4d"), so a loose search would
 * either stop at the numeric core or swallow the "-Setup" suffix.
 */
const INSTALLER_NAME_RE =
  /^Checkpoint-(?:Windows-x64|Linux-amd64|macOS-(?:x64|arm64))-(.+)\.(?:exe|deb|rpm|pkg|dmg)$/;
const SEMVER_RE = /^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/;

export function extractVersionFromFilename(name: string): string | null {
  const match = name.match(INSTALLER_NAME_RE);
  if (!match) return null;

  // The NSIS artifact name appends "-Setup" after the version.
  const version = match[1].replace(/-Setup$/, "");
  return SEMVER_RE.test(version) ? version : null;
}

/**
 * Version a release actually ships.
 *
 * The release stream tags each build `v<semver>`, so the tag is authoritative.
 * The nightly stream reuses one rolling tag ("nightly") whose name says nothing
 * about the version, so fall back to reading it out of the installer filenames
 * attached to the release.
 */
function resolveReleaseVersion(release: GitHubRelease): string | null {
  if (/^v?\d+\.\d+\.\d+/.test(release.tag_name)) {
    return release.tag_name.replace(/^v/, "");
  }

  for (const asset of release.assets) {
    const version = extractVersionFromFilename(asset.name);
    if (version) return version;
  }

  return null;
}

/**
 * Semver precedence, including prereleases. Needed for the nightly channel:
 * every nightly version is a prerelease, so a numeric-only comparison reads
 * "0.5.0-nightly.202609030800" as NaN and never sees a newer build.
 *
 * Follows semver.org rule 11: compare the numeric core, then treat a version
 * with a prerelease as lower than the same core without one, then compare
 * prerelease identifiers left to right (numeric identifiers compare
 * numerically and rank below alphanumeric ones).
 */
export function compareVersions(a: string, b: string): number {
  const parse = (v: string): { core: number[]; pre: string[] } => {
    // Build metadata (+...) is ignored for precedence.
    const cleaned = v.replace(/^v/, "").split("+")[0];
    const dash = cleaned.indexOf("-");
    const core = (dash === -1 ? cleaned : cleaned.slice(0, dash))
      .split(".")
      .map((n) => parseInt(n, 10) || 0);
    const pre = dash === -1 ? [] : cleaned.slice(dash + 1).split(".");
    return { core, pre };
  };

  const va = parse(a);
  const vb = parse(b);

  for (let i = 0; i < Math.max(va.core.length, vb.core.length); i++) {
    const na = va.core[i] ?? 0;
    const nb = vb.core[i] ?? 0;
    if (na > nb) return 1;
    if (na < nb) return -1;
  }

  // A release outranks any prerelease of the same core version.
  if (va.pre.length === 0 && vb.pre.length === 0) return 0;
  if (va.pre.length === 0) return 1;
  if (vb.pre.length === 0) return -1;

  for (let i = 0; i < Math.max(va.pre.length, vb.pre.length); i++) {
    const ia = va.pre[i];
    const ib = vb.pre[i];
    // A shorter identifier set is lower, all preceding identifiers being equal.
    if (ia === undefined) return -1;
    if (ib === undefined) return 1;
    if (ia === ib) continue;

    const numA = /^\d+$/.test(ia);
    const numB = /^\d+$/.test(ib);
    if (numA && numB) {
      const diff = parseInt(ia, 10) - parseInt(ib, 10);
      if (diff !== 0) return diff > 0 ? 1 : -1;
      continue;
    }
    if (numA) return -1;
    if (numB) return 1;
    return ia > ib ? 1 : -1;
  }

  return 0;
}

function httpsGet(url: string): Promise<{
  statusCode: number;
  headers: http.IncomingHttpHeaders;
  body: string;
}> {
  return new Promise((resolve, reject) => {
    const makeRequest = (reqUrl: string, redirectCount: number): void => {
      if (redirectCount > 5) {
        reject(new Error("Too many redirects"));
        return;
      }

      https
        .get(
          reqUrl,
          {
            headers: {
              "User-Agent": "Checkpoint-Daemon-Updater",
              Accept: "application/vnd.github+json",
            },
          },
          (res) => {
            if (
              res.statusCode &&
              res.statusCode >= 300 &&
              res.statusCode < 400 &&
              res.headers.location
            ) {
              makeRequest(res.headers.location, redirectCount + 1);
              return;
            }

            let body = "";
            res.on("data", (chunk: Buffer) => {
              body += chunk.toString();
            });
            res.on("end", () => {
              resolve({
                statusCode: res.statusCode ?? 0,
                headers: res.headers,
                body,
              });
            });
            res.on("error", reject);
          },
        )
        .on("error", reject);
    };

    makeRequest(url, 0);
  });
}

function downloadFile(
  url: string,
  destPath: string,
  onProgress: (downloaded: number, total: number) => void,
): Promise<void> {
  return new Promise((resolve, reject) => {
    const makeRequest = (reqUrl: string, redirectCount: number): void => {
      if (redirectCount > 5) {
        reject(new Error("Too many redirects"));
        return;
      }

      const proto = reqUrl.startsWith("https") ? https : http;
      proto
        .get(
          reqUrl,
          {
            headers: { "User-Agent": "Checkpoint-Daemon-Updater" },
          },
          (res) => {
            if (
              res.statusCode &&
              res.statusCode >= 300 &&
              res.statusCode < 400 &&
              res.headers.location
            ) {
              makeRequest(res.headers.location, redirectCount + 1);
              return;
            }

            if (res.statusCode !== 200) {
              reject(
                new Error(`Download failed with status ${res.statusCode}`),
              );
              return;
            }

            const totalSize = parseInt(
              res.headers["content-length"] ?? "0",
              10,
            );
            let downloaded = 0;

            const file = createWriteStream(destPath);
            res.on("data", (chunk: Buffer) => {
              downloaded += chunk.length;
              onProgress(downloaded, totalSize);
            });
            res.pipe(file);
            file.on("finish", () => {
              file.close();
              resolve();
            });
            file.on("error", (err) => {
              fs.unlink(destPath).catch(() => {});
              reject(err);
            });
            res.on("error", (err) => {
              fs.unlink(destPath).catch(() => {});
              reject(err);
            });
          },
        )
        .on("error", reject);
    };

    makeRequest(url, 0);
  });
}

export class Updater {
  private config: UpdaterConfig;
  private status: UpdateStatus;
  private checkInterval: ReturnType<typeof setInterval> | null = null;

  constructor(config?: Partial<UpdaterConfig>) {
    this.config = { ...DEFAULT_CONFIG, ...config };
    this.status = {
      currentVersion: getCurrentVersion(),
      latestVersion: null,
      updateAvailable: false,
      checking: false,
      downloading: false,
      downloadProgress: 0,
      downloadedInstallerPath: null,
      lastCheckTime: null,
      lastError: null,
      channel: this.config.channel,
    };
  }

  /**
   * GitHub API endpoint for the newest build on the configured channel.
   *
   * The release stream can use /releases/latest because the nightly release is
   * published with make_latest:false and therefore never occupies that slot.
   * The nightly stream reads its fixed rolling tag instead, which is rebuilt in
   * place on every client-affecting change.
   */
  private releaseUrl(): string {
    const base = `https://api.github.com/repos/${this.config.repository}/releases`;
    return this.config.channel === "nightly"
      ? `${base}/tags/${this.config.nightlyTag}`
      : `${base}/latest`;
  }

  public getChannel(): UpdateChannel {
    return this.config.channel;
  }

  /**
   * Switch delivery streams and re-check immediately.
   *
   * Note that moving from nightly back to release does not downgrade: a machine
   * running 0.5.0-nightly.* sits above the released 0.4.x until 0.5.0 ships, so
   * it simply reports "up to date" until the stable stream catches up.
   */
  public async setChannel(channel: UpdateChannel): Promise<UpdateStatus> {
    if (this.config.channel === channel) {
      return this.getStatus();
    }

    Logger.info(
      `Switching update channel: ${this.config.channel} -> ${channel}`,
    );
    this.config.channel = channel;
    this.status.channel = channel;
    this.status.latestVersion = null;
    this.status.updateAvailable = false;
    this.status.downloadedInstallerPath = null;
    this.status.lastError = null;

    try {
      const vars = await DaemonConfig.Get();
      vars.updates = { ...vars.updates, channel };
      await DaemonConfig.Save();
    } catch (err) {
      // A failed write only costs the choice its persistence across restarts,
      // so keep the switch active for this session rather than rolling back.
      Logger.warn(
        `Could not persist the update channel to daemon.json: ${
          err instanceof Error ? err.message : String(err)
        }`,
      );
    }

    return await this.checkForUpdates();
  }

  public start(): void {
    if (!this.config.enabled) {
      Logger.info("Auto-update checking is disabled");
      return;
    }

    Logger.info(
      `Starting update checker (interval: ${this.config.checkIntervalMs / 1000 / 60}min, repo: ${this.config.repository})`,
    );

    // Check immediately on start, then on interval
    void this.checkForUpdates();

    this.checkInterval = setInterval(() => {
      void this.checkForUpdates();

      // Prune installers left over from prior updates, even when auto-checking is
      // disabled. After applyUpdate() the daemon exits and the freshly installed
      // build starts here, so this removes the installer that was just applied
      // (now equal to the current version) along with any older leftovers.
      void this.cleanupOldInstallers();
    }, this.config.checkIntervalMs);
  }

  public stop(): void {
    if (this.checkInterval) {
      clearInterval(this.checkInterval);
      this.checkInterval = null;
    }
  }

  public getStatus(): UpdateStatus {
    return { ...this.status };
  }

  public async checkForUpdates(): Promise<UpdateStatus> {
    if (this.status.checking) {
      return this.getStatus();
    }

    this.status.checking = true;
    this.status.lastError = null;

    try {
      const url = this.releaseUrl();
      Logger.info(
        `Checking for updates on the ${this.config.channel} channel: ${url}`,
      );

      const response = await httpsGet(url);

      if (response.statusCode === 404 && this.config.channel === "nightly") {
        // No nightly has been published yet (or the tag was removed).
        Logger.info(
          `No release found on tag "${this.config.nightlyTag}"; nothing to update to`,
        );
        this.status.lastCheckTime = Date.now();
        this.status.updateAvailable = false;
        return this.getStatus();
      }

      if (response.statusCode !== 200) {
        throw new Error(
          `GitHub API returned status ${response.statusCode}: ${response.body.substring(0, 200)}`,
        );
      }

      const release = JSON.parse(response.body) as GitHubRelease;

      // Drafts are never installable. Prereleases are the whole point of the
      // nightly channel, but must stay out of the release channel.
      if (release.draft) {
        Logger.info("Latest release is a draft, skipping");
        this.status.lastCheckTime = Date.now();
        return this.getStatus();
      }
      if (release.prerelease && this.config.channel === "release") {
        Logger.info("Latest release is a prerelease, skipping");
        this.status.lastCheckTime = Date.now();
        return this.getStatus();
      }

      const latestVersion = resolveReleaseVersion(release);
      this.status.lastCheckTime = Date.now();

      if (!latestVersion) {
        Logger.warn(
          `Could not determine a version for release "${release.tag_name}" (${release.assets.length} assets)`,
        );
        this.status.updateAvailable = false;
        return this.getStatus();
      }

      this.status.latestVersion = latestVersion;

      if (compareVersions(latestVersion, this.status.currentVersion) > 0) {
        this.status.updateAvailable = true;
        Logger.info(
          `Update available: ${this.status.currentVersion} → ${latestVersion}`,
        );
      } else {
        this.status.updateAvailable = false;
        Logger.info(
          `Up to date (current: ${this.status.currentVersion}, latest: ${latestVersion})`,
        );
      }
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      this.status.lastError = message;
      Logger.error(`Update check failed: ${message}`);
    } finally {
      this.status.checking = false;
    }

    return this.getStatus();
  }

  public async downloadUpdate(): Promise<string | null> {
    if (!this.status.updateAvailable || !this.status.latestVersion) {
      Logger.warn("No update available to download");
      return null;
    }

    if (this.status.downloading) {
      Logger.warn("Download already in progress");
      return null;
    }

    this.status.downloading = true;
    this.status.downloadProgress = 0;
    this.status.lastError = null;

    try {
      // Fetch release info again to get asset URLs
      const url = this.releaseUrl();
      const response = await httpsGet(url);

      if (response.statusCode !== 200) {
        throw new Error(`GitHub API returned status ${response.statusCode}`);
      }

      const release = JSON.parse(response.body) as GitHubRelease;
      const pattern = getInstallerAssetPattern();

      if (!pattern) {
        throw new Error(`Unsupported platform: ${platform()}-${arch()}`);
      }

      const regex = new RegExp(pattern);
      const asset = release.assets.find((a) => regex.test(a.name));

      if (!asset) {
        throw new Error(
          `No installer asset found for ${platform()}-${arch()} in release ${release.tag_name}`,
        );
      }

      Logger.info(`Downloading update: ${asset.name} (${asset.size} bytes)`);

      const downloadDir = path.join(homedir(), ".checkpoint", "updates");
      await fs.mkdir(downloadDir, { recursive: true });

      const destPath = path.join(downloadDir, asset.name);

      await downloadFile(
        asset.browser_download_url,
        destPath,
        (downloaded, total) => {
          this.status.downloadProgress =
            total > 0 ? Math.round((downloaded / total) * 100) : 0;
        },
      );

      this.status.downloadedInstallerPath = destPath;
      this.status.downloadProgress = 100;
      Logger.info(`Update downloaded to: ${destPath}`);

      return destPath;
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      this.status.lastError = message;
      Logger.error(`Download failed: ${message}`);
      return null;
    } finally {
      this.status.downloading = false;
    }
  }

  public async applyUpdate(): Promise<void> {
    const installerPath = this.status.downloadedInstallerPath;

    if (!installerPath || !existsSync(installerPath)) {
      throw new Error("No downloaded installer available");
    }

    Logger.info(`Applying update from: ${installerPath}`);

    const p = platform();

    // Launch the installer as a detached process and exit the daemon.
    // The installer will stop the old service, install the new version,
    // and start the new service.
    const { spawn } = await import("child_process");

    switch (p) {
      case "win32": {
        // The NSIS installer is perMachine + assisted (oneClick:false), so its
        // manifest requires administrator elevation. The daemon runs as a
        // non-elevated per-user process (the tray launches it), so spawning the
        // installer directly via CreateProcess fails: Windows returns
        // ERROR_ELEVATION_REQUIRED, which libuv surfaces as EACCES. Launch it
        // through ShellExecute's "runas" verb via PowerShell's Start-Process so
        // the UAC elevation flow runs. /S keeps the installer silent.
        const psInstallerPath = installerPath.replace(/'/g, "''");
        spawn(
          "powershell.exe",
          [
            "-NoProfile",
            "-Command",
            `Start-Process -FilePath '${psInstallerPath}' -ArgumentList '/S' -Verb RunAs`,
          ],
          {
            detached: true,
            stdio: "ignore",
            windowsHide: true,
          },
        ).unref();
        break;
      }

      case "darwin":
        // macOS .pkg can be installed with the `installer` command
        spawn("sudo", ["installer", "-pkg", installerPath, "-target", "/"], {
          detached: true,
          stdio: "ignore",
        }).unref();
        break;

      case "linux":
        if (installerPath.endsWith(".deb")) {
          spawn("sudo", ["dpkg", "-i", installerPath], {
            detached: true,
            stdio: "ignore",
          }).unref();
        } else if (installerPath.endsWith(".rpm")) {
          spawn("sudo", ["rpm", "-U", installerPath], {
            detached: true,
            stdio: "ignore",
          }).unref();
        }
        break;
    }

    // Give the installer a moment to start, then exit
    Logger.info("Installer launched, daemon will exit for update...");
    setTimeout(() => {
      process.exit(0);
    }, 2000);
  }

  /**
   * Permanently delete stale installers in ~/.checkpoint/updates. Any file
   * whose embedded version is the current version or older is removed; only
   * installers strictly newer than what we're running (a pending update) are
   * kept. fs.rm deletes in place and never routes through the OS recycle
   * bin/trash, so this satisfies the "skip recycle bin" requirement.
   */
  public async cleanupOldInstallers(): Promise<void> {
    const updatesDir = path.join(homedir(), ".checkpoint", "updates");

    let entries: string[];
    try {
      entries = await fs.readdir(updatesDir);
    } catch (err) {
      // Nothing downloaded yet: the directory simply doesn't exist.
      if ((err as NodeJS.ErrnoException).code === "ENOENT") return;
      Logger.warn(
        `Could not read updates dir for cleanup: ${
          err instanceof Error ? err.message : String(err)
        }`,
      );
      return;
    }

    const current = this.status.currentVersion;

    for (const name of entries) {
      const version = extractVersionFromFilename(name);
      // Leave anything we can't identify as a versioned installer untouched.
      if (!version) continue;

      // Keep installers strictly newer than the running version.
      if (compareVersions(version, current) > 0) continue;

      const filePath = path.join(updatesDir, name);
      try {
        await fs.rm(filePath, { force: true });
        Logger.info(
          `Removed stale installer: ${name} (v${version} <= v${current})`,
        );

        // Forget the tracked installer if we just deleted it.
        if (this.status.downloadedInstallerPath === filePath) {
          this.status.downloadedInstallerPath = null;
        }
      } catch (err) {
        Logger.warn(
          `Failed to remove stale installer ${name}: ${
            err instanceof Error ? err.message : String(err)
          }`,
        );
      }
    }
  }
}

// Singleton instance
let updaterInstance: Updater | null = null;

export function getUpdater(config?: Partial<UpdaterConfig>): Updater {
  if (!updaterInstance) {
    updaterInstance = new Updater(config);
  }
  return updaterInstance;
}
